### ISSUE TITLE
bdist limitation

### ISSUE THREAD

**Issue by kcpevey** [Quansight/numpy-threading-extensions#52]
@mattip Is there a reason why we have `bdist` limited to 3.6 in `setup.cfg`

```
[bdist_wheel]
py-limited-api = cp36
```

**Comment by mattip** [comment]
If we remove this requirement, we need to create a wheel for each version of python we wish to support. Since we do not use much of the python C-API, we can create a stable API binary package (see [PEP 384](https://www.python.org/dev/peps/pep-0384/)). That is done using this definition. The wheel name should be something like `fast_numpy_loops-0.0.0-cp36-abi3-linux_x86_64.whl`, where the `cp36-abi3` means this wheel can be installed on *any* python >=3.6 (it still needs to be used on `linux_x6_64`. After processing with `auditwheel`, if built in a proper manylinux docker, it can use the `fast_numpy_loops-0.0.0-cp36-abi3-manylinux1.whl` name). The dll inside the package is called `_fast_numpy_loops.abi3.so`, which also indicates it uses the stable API.

**Comment by mattip** [comment]
We define the [`Py_LIMITED_API` macro](https://github.com/Quansight/numpy-threading-extensions/blob/main/setup.py#L28) as well

**Comment by kcpevey** [comment]
Ok. I didn't understand the naming convention. So if we include the above setup, then we build using py 3.8, it will build a wheel compatible for 3.6, 3.7 and 3.8?

**Comment by mattip** [comment]
Assuming cibuildwheel supports that, yes

**Comment by mattip** [comment]
And 3.9, 3.10, ...

**Comment by mattip** [comment]
Xref joerick/cibuildwheel#78

**Comment by mattip** [comment]
Closing, the question was answered.
